version: '3'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
      - PLEX_CLAIM=claim-BXCpiRzdsz2PUfZnTyAn
    network_mode: host
    volumes:
      - /var/lib/plexmediaserver:/config
      - /tmp:/transcode
      - /mnt/vault1:/mnt/vault1
      - /mnt/vault2:/mnt/vault2

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    network_mode: host
    volumes:
      - /var/lib/jellyfin/config:/config
      - /var/lib/jellyfin/cache:/cache
      - /mnt/vault1:/mnt/vault1
      - /mnt/vault2:/mnt/vault2
