version: '3'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
      - PLEX_CLAIM=claim-BXCpiRzdsz2PUfZnTyAn
    network_mode: host
    volumes:
      - /var/lib/plexmediaserver:/config
      - /tmp:/transcode
      - /mnt/vault1:/mnt/vault1
      - /mnt/vault2:/mnt/vault2

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    network_mode: host
    volumes:
      - /var/lib/jellyfin/config:/config
      - /var/lib/jellyfin/cache:/cache
      - /mnt/vault1:/mnt/vault1
      - /mnt/vault2:/mnt/vault2

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /var/lib/jellyseerr/config:/app/config
    restart: unless-stopped
    network_mode: host

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /var/lib/radarr/config:/config
      - /mnt/vault1:/mnt/vault1
      - /mnt/vault2:/mnt/vault2
    restart: unless-stopped
    network_mode: host

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /var/lib/prowlarr/config:/config
    restart: unless-stopped
    network_mode: host

  transmission-vpn:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-vpn
    env_file: .env
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_CONFIG=us-atl.prod.surfshark.com_udp  # or another server of your choice
      - LOCAL_NETWORK=192.168.0.0/16,172.16.0.0/12
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME}
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD}
      - TRANSMISSION_DOWNLOAD_DIR=/mnt/vault1/Unsorted
      - TRANSMISSION_INCOMPLETE_DIR=/mnt/vault1/Downloads
      - TRANSMISSION_WATCH_DIR=/downloads/watch
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /var/lib/transmission-daemon/.config/transmission-daemon:/config
      - /mnt/vault1/Unsorted:/mnt/vault1/Unsorted
      - /mnt/vault1/Downloads:/mnt/vault1/Downloads
    network_mode: bridge