version: '3'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
      - PLEX_CLAIM=claim-BXCpiRzdsz2PUfZnTyAn
    network_mode: host
    volumes:
      - /var/lib/plexmediaserver:/config
      - /tmp:/transcode
      - /mnt/valut1:/mnt/vault1
      - /mnt/valut2:/mnt/vault2
